const programmes = [
  {
    id: "putting-performance",
    type: "practice",
    title: "Putting Performance",
    strapline: "Build a repeatable stroke and turn practice-green work into lower scores.",
    summary: "A structured putting programme combining start-line control, pace training and pressure-based scoring games.",
    weeks: 4,
    sessions: 8,
    minutes: "25–40",
    level: "All golfers",
    equipment: "Putter, balls, tees and a practice green",
    price: "£9.99",
    accent: "lime",
    number: "01",
    outcomes: ["Start the ball on your chosen line", "Develop reliable pace from varied distances", "Practise with meaningful targets and pressure"],
    includes: ["Eight guided sessions", "Scored drills and progress tracking", "Indoor and outdoor alternatives", "ForeThought-compatible JSON file"]
  },
  {
    id: "wedge-distance-control",
    type: "practice",
    title: "Wedge Distance Control",
    strapline: "Turn the scoring zone into a set of predictable, playable numbers.",
    summary: "Build a practical wedge matrix, improve strike and learn to control carry through changing swing lengths.",
    weeks: 4,
    sessions: 8,
    minutes: "35–50",
    level: "Improving golfers",
    equipment: "Wedges, balls and measured targets",
    price: "£12.99",
    accent: "orange",
    number: "02",
    outcomes: ["Map dependable carry distances", "Improve strike and launch consistency", "Choose safer scoring shots on the course"],
    includes: ["Eight guided sessions", "Wedge-matrix assessment", "Random and blocked practice", "ForeThought-compatible JSON file"]
  },
  {
    id: "gir-builder",
    type: "practice",
    title: "GIR Builder",
    strapline: "Train the approach shots that create more stress-free pars.",
    summary: "A focused iron-practice plan built around target selection, dispersion, strike and realistic approach-shot challenges.",
    weeks: 6,
    sessions: 12,
    minutes: "40–55",
    level: "Club golfers",
    equipment: "Irons, balls and range targets",
    price: "£14.99",
    accent: "blue",
    number: "03",
    outcomes: ["Improve centred contact", "Understand useful shot dispersion", "Make better target decisions"],
    includes: ["Twelve guided sessions", "Baseline and final assessments", "Variable target challenges", "ForeThought-compatible JSON file"]
  },
  {
    id: "golf-mobility-foundations",
    type: "fitness",
    title: "Golf Mobility Foundations",
    strapline: "Move more freely through the positions your golf swing actually needs.",
    summary: "A progressive mobility plan for hips, thoracic spine, shoulders and ankles, designed around golf movement.",
    weeks: 4,
    sessions: 12,
    minutes: "15–25",
    level: "All golfers",
    equipment: "Mat, resistance band and light club",
    price: "£9.99",
    accent: "purple",
    number: "04",
    outcomes: ["Create easier rotation", "Improve useful range of motion", "Build a sustainable warm-up habit"],
    includes: ["Twelve guided sessions", "Clear exercise instructions", "Short pre-round options", "Lesson Logger-compatible JSON file"]
  },
  {
    id: "strength-for-golf",
    type: "fitness",
    title: "Strength for Golf",
    strapline: "Build the physical foundations for a stronger, more resilient swing.",
    summary: "A simple progressive strength programme that prioritises the legs, trunk, upper back and rotational control.",
    weeks: 6,
    sessions: 12,
    minutes: "35–50",
    level: "Intermediate",
    equipment: "Dumbbells, resistance band and bench",
    price: "£14.99",
    accent: "red",
    number: "05",
    outcomes: ["Develop useful lower-body strength", "Improve trunk control", "Build tolerance for golf and practice volume"],
    includes: ["Twelve guided workouts", "Progressive sets and repetitions", "Exercise substitutions", "Lesson Logger-compatible JSON file"]
  },
  {
    id: "winter-golf-engine",
    type: "fitness",
    title: "Winter Golf Engine",
    strapline: "Arrive at the new season ready to play, not ready to begin.",
    summary: "A balanced off-season programme combining strength, mobility and conditioning for golfers training through winter.",
    weeks: 8,
    sessions: 24,
    minutes: "30–55",
    level: "Committed golfers",
    equipment: "Basic gym equipment",
    price: "£19.99",
    accent: "ice",
    number: "06",
    outcomes: ["Maintain golf-specific capacity", "Build a stronger movement base", "Return to play progressively"],
    includes: ["Twenty-four guided workouts", "Three sessions per week", "Recovery-aware progression", "Lesson Logger-compatible JSON file"]
  }
];

window.ForeThoughtProgrammes = programmes;
